default:
    root_dir: <%= File.expand_path('../', __FILE__) %>
    config_dir: config
    yaml_dir: config/yaml
    media_dir: media

database:
  sqlite:
    path: "db/items.db"
  mongodb:
    host: "localhost"
    port: 27017
    database_name: "items_db"